### ISSUE TITLE
v1.18.3 not found

### ISSUE THREAD

**Issue by asdf2014** [uzxmx/dockerhub-build-trigger#1]
Please update these images

**Comment by asdf2014** [comment]
@uzxmx PTAL

**Comment by uzxmx** [comment]
@asdf2014 Sorry for the delay. Just updated kubernetes images of v1.18.3, you should be able to find them now. And I've triggered a synchronization from v1.16.7 to the latest version. So after a while, all versions between v1.16.7 and the latest version should be available.
